controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

create_portal_session:
    path: /create-portal-session
    controller: App\Controller\StripeController::createPortalSession
    methods: [POST]

